project_id = "kzlmfsvdakgvotuxxcgl"

[functions.extract-report-fields]
verify_jwt = true

[functions.generate-note-summary]
verify_jwt = true

[functions.test-openai]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.suggest-tasks]
verify_jwt = false

[functions.label-photo]
verify_jwt = false
